name: Build Stream Deck Plugin

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build, Pack and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

#      - name: Lint
#        run: npm run lint

      - name: Pack Stream Deck Plugin
        uses: neilenns/streamdeck-cli-pack@v1

      - name: Verify generated package
        run: |
          echo "Generated files:"
          ls -lah
          find . -name "*.streamDeckPlugin"

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: stream-deck-plugin
          path: "*.streamDeckPlugin"
          if-no-files-found: error
          retention-days: 30
